### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by svandragt** [silverstripe-labs/silverstripe-dms#49]
Would be great to see actual releases for this module. It's great functionality but problems like https://github.com/silverstripe-labs/silverstripe-dms/pull/48 show that there should be options for stable release upgrading (at least less unstable)?

**Comment by jaedb** [comment]
Ditto. It'd be great to be able to use Composer with best practices version tagging.

**Comment by sheadawson** [comment]
+1

**Comment by jaedb** [comment]
Has there been any progress on this? DMS is in use on many production environments (not just ours) and it seems crazy that these processes are not in use.

**Comment by monkeyfeet** [comment]
Agree

**Comment by dhensby** [comment]
Hey, I agree - we need to get a tag out.

I'm not that familiar with this module but I'll do my best.

At the moment there are 2 branches, `1.0` and `master`. I can tag a `v1.0.0` release from `1.0` and I can look at master and see if that has breaking changes (if it does, then I'll do `v2.0.0`, if not then I'll do `v1.1.0`).

Depending on the above I may create a couple other branches too, like `2` and `2.0` and we can mark v1 as unsupported...

Which version are you using and does that make sense?

**Comment by svandragt** [comment]
I'm tracking the master version. I'm not in a position to give you much feedback regarding your tagging choices but v1.1.0 and v2.0.0 seems to make sense. This should help implementers like myself upgrade to newer stable versions.

**Comment by jaedb** [comment]
I agree with @svandragt

**Comment by dhensby** [comment]
Right - I've tagged a 1.0.0 release and I'm comparing [master and 1.0](https://github.com/silverstripe-labs/silverstripe-dms/compare/1.0...master?w=1) and actually can't see anything that would warrant a 2.0

Would anyone here be prepared to test this for me on a real project and swap 1.0 in and see if that breaks anything?

If it breaks I'll do 2.0.0 otherwise I'll do 1.1.0 (I think some features were added, but nothing broken)

**Comment by dhensby** [comment]
Hmm, I've just looked through all the PRs since 1.0 was last updated and I can't see anything that I'd consider not a patch - I'll give some time for feedback and then will tag a v1.1.0 as long as no one here objects.

**Comment by kinglozzer** [comment]
@dhensby If it helps, I just upgraded from [this commit](https://github.com/silverstripe-labs/silverstripe-dms/commit/86384406602f89763b15bd536e855945160f4b8b) (which is pre-1.0.0) to the latest commit on master on a 3.1 site and didn’t experience any breakages in anything I tested. I’ve not tested on 3.2 or 3.3, though

**Comment by dhensby** [comment]
OK, that's what I'd have expected, I'll tag a 1.1 release, then

**Comment by xini** [comment]
can you please tag another version with the latest fixes for SS32+? Thanks.

**Comment by dhensby** [comment]
v1.1.1 and v1.2.0 released - v1.2.0 has 3.2 fixes in.

**Comment by xini** [comment]
Thanks!

**Comment by dhensby** [comment]
@xini feel free to open issues when you need new tags or just ask at the end of  a PR :)
