### ISSUE TITLE
Doesn't work with silverstripe 3.1.x-dev.

### ISSUE THREAD

**Issue by robbyahn** [silverstripe-labs/silverstripe-dms#69]
Doesn't work with silverstripe 3.1.x-dev.

composer installed following command: 
$> composer require silverstripe/dms dev-master

 Problem 1
    - Can only install one of: silverstripe/cms[3.1.15, 3.1.x-dev].
    - Can only install one of: silverstripe/cms[3.1.x-dev, 3.1.15].
    - Can only install one of: silverstripe/cms[3.1.15, 3.1.x-dev].
    - Installation request for silverstripe/cms 3.1.15.0 -> satisfiable by silverstripe/cms[3.1.15].
    - Installation request for silverstripe/cms == 3.1.9999999.9999999-dev -> satisfiable by silverstripe/cms[3.1.x-dev].

**Comment by dhensby** [comment]
@robbyahn what does your composer file look like?

**Comment by dhensby** [comment]
This composer file worked for me:

```json
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.2",
		"silverstripe/cms": "3.1.x-dev",
		"silverstripe/framework": "3.1.x-dev",
		"silverstripe-themes/simple": "*",
		"silverstripe/dms": "dev-master"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"config": {
		"process-timeout": 600
	},
	"minimum-stability": "dev"
}
```

**Comment by dhensby** [comment]
I'm going to close this as I can't replicate, if you still have the problem, feel free to re-open and share your composer.json file
