### ISSUE TITLE
Incompatible with SilverStripe 3.3.1

### ISSUE THREAD

**Issue by jaedb** [silverstripe-labs/silverstripe-dms#80]
- Cannot work on SilverStripe 3.3.1 due to issue with `GridFieldOrderableRows`
- User error flagged: `Couldn't find the sort field 'DocumentSort'`
- Resolved in Pull Request #79

**Comment by mrmorphic** [comment]
This may be related to a framework fix in PR https://github.com/silverstripe/silverstripe-framework/pull/5010

As far as I understand it, this was merged into 3.2, but due to the way the branches are managed, it is not on 3.3.1 but should be on later releases. You'll need to check the details.

The issue that is fixed in this PR is that under certain circumstances, the framework doesn't return the extra fields in a many-many relationship, and this propagates to dms. I don't think this is an issue in dms itself.

**Comment by jaedb** [comment]
@mrmorphic Ah, thanks for the explanation.

I think it does remain an issue with DMS itself as currently it requires a third-party plugin (`GridFieldOrderableRows` class) which is not explicitly required in the composer.json file.

**Comment by mrmorphic** [comment]
I'd agree, if it has that dependency, it should be declared.

**Comment by xini** [comment]
also see https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/134

**Comment by xini** [comment]
also see https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/134

**Comment by dhensby** [comment]
I've just tested on latest 3.x-dev and can't replicate an issue.

Please can you provide your exact steps?

**Comment by xini** [comment]
I tested in both 3.3.1 and 3.x-dev. In 3.3.1 the error was there, not so in 3.x-dev. I guess https://github.com/silverstripe/silverstripe-framework/commit/745faebd81a868d319f7000fe880c23d4e99fd1b has resolved this.

**Comment by xini** [comment]
Is that going to go into 3.3.2?

**Comment by dhensby** [comment]
That commit is a merge commit into master, so I'm not sure that's the relevant fix. the 3.3 branch will make the net 3.3.2 release.

3 branch will become 3.4.0

**Comment by xini** [comment]
Well, can you make sure it goes into 3.3.2? This is a bug fix, not a new feature and has been broken since 3.2.0, even though minor releases should not break anything. Thanks.

**Comment by dhensby** [comment]
You linked to a merge commit. That's not a big fix and its a whole load of unrelated changes. 

If you let me know which PR fixed the issue, I can look at bringing it into 3.3, though it will probably miss 3.3.2 which will be released soon

**Comment by xini** [comment]
This is the one: https://github.com/silverstripe/silverstripe-framework/pull/5010. Thanks.

**Comment by dhensby** [comment]
That was merged into 3.2 which means it will be part of the next 3.3 release.

**Comment by xini** [comment]
great. thanks.
